"""
PDF inspection report generator.

Produces one report for both kinds of inspection, because they answer
different questions and the old single-layout version only really fitted
images:

  * an IMAGE inspection is a set of independent photos — each one is its own
    scene, so every image gets its own detail block;
  * a VIDEO inspection is one continuous scene sampled into frames. The
    interesting unit is the *worker tracked across the whole clip*, not any
    individual frame, and labelling 300 frames as "Total Images" (as the old
    report did) actively misleads.

Everything is defensive about missing keys and missing files: reports are
generated from records that may have been written by older versions of the
pipeline, and a report that renders with a gap is far more useful than one
that raises halfway through.
"""

import os

from risk_engine import assess_risk, get_recommendations
from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import cm
from reportlab.lib.utils import ImageReader
from reportlab.platypus import (
    Image,
    KeepTogether,
    PageBreak,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

# ----------------------------------------------------------------------
# Look and feel
# ----------------------------------------------------------------------
BRAND = colors.HexColor("#dc2626")
INK = colors.HexColor("#0f172a")
MUTED = colors.HexColor("#64748b")
LINE = colors.HexColor("#e2e8f0")
PANEL = colors.HexColor("#f8fafc")
GREEN = colors.HexColor("#15803d")
AMBER = colors.HexColor("#a16207")
RED = colors.HexColor("#dc2626")

PPE_ITEMS = [
    ("helmet", "Helmet"),
    ("vest", "Vest"),
    ("gloves", "Gloves"),
    ("boots", "Boots"),
    ("goggles", "Goggles"),
]

# Frames rendered in full in a video report. A sampled video can retain
# dozens of result frames; every one of them at full width would produce a
# 40-page PDF that nobody reads. Violation frames are prioritised because
# they're the evidence that matters.
MAX_VIDEO_FRAMES_IN_REPORT = 8


def _tone(compliance):
    """Colour for a compliance percentage."""
    try:
        value = float(compliance)
    except (TypeError, ValueError):
        return MUTED
    if value >= 90:
        return GREEN
    if value >= 70:
        return AMBER
    return RED


def _styles():
    base = getSampleStyleSheet()
    return {
        "title": ParagraphStyle(
            "title", parent=base["Title"], fontName="Helvetica-Bold",
            fontSize=22, leading=26, textColor=INK, alignment=TA_CENTER, spaceAfter=2,
        ),
        "subtitle": ParagraphStyle(
            "subtitle", parent=base["Normal"], fontSize=10, leading=14,
            textColor=MUTED, alignment=TA_CENTER, spaceAfter=16,
        ),
        "h2": ParagraphStyle(
            "h2", parent=base["Heading2"], fontName="Helvetica-Bold",
            fontSize=13, leading=16, textColor=INK, spaceBefore=14, spaceAfter=6,
        ),
        "h3": ParagraphStyle(
            "h3", parent=base["Heading3"], fontName="Helvetica-Bold",
            fontSize=11, leading=14, textColor=INK, spaceBefore=10, spaceAfter=4,
        ),
        "body": ParagraphStyle(
            "body", parent=base["Normal"], fontSize=9.5, leading=13, textColor=INK,
        ),
        "muted": ParagraphStyle(
            "muted", parent=base["Normal"], fontSize=8.5, leading=12, textColor=MUTED,
        ),
        "caption": ParagraphStyle(
            "caption", parent=base["Normal"], fontSize=8.5, leading=11,
            textColor=MUTED, alignment=TA_CENTER, spaceBefore=3,
        ),
    }


def _page_furniture(canvas, doc):
    """Brand rule at the top, page number and attribution at the bottom."""
    canvas.saveState()
    width, height = A4

    canvas.setStrokeColor(BRAND)
    canvas.setLineWidth(2)
    canvas.line(2 * cm, height - 1.5 * cm, width - 2 * cm, height - 1.5 * cm)

    canvas.setFont("Helvetica", 7.5)
    canvas.setFillColor(MUTED)
    canvas.drawString(2 * cm, height - 1.15 * cm, "SAFESIGHT — AI Workplace Safety Monitoring")
    canvas.drawRightString(width - 2 * cm, 1.2 * cm, f"Page {canvas.getPageNumber()}")
    canvas.drawString(2 * cm, 1.2 * cm, "Generated by Safesight AI · automated detection, review before action")
    canvas.restoreState()


def _kv_table(rows, col_widths):
    """Two-column label/value table used for the metadata blocks."""
    table = Table(rows, colWidths=col_widths, hAlign="LEFT")
    table.setStyle(TableStyle([
        ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
        ("FONTNAME", (1, 0), (1, -1), "Helvetica"),
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("TEXTCOLOR", (0, 0), (0, -1), MUTED),
        ("TEXTCOLOR", (1, 0), (1, -1), INK),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ("TOPPADDING", (0, 0), (-1, -1), 4),
        ("LINEBELOW", (0, 0), (-1, -2), 0.4, LINE),
    ]))
    return table


def _kpi_row(summary, is_video):
    """The four headline numbers, compliance colour-coded."""
    compliance = summary.get("compliance", 0)
    cells = [
        ("Frames analysed" if is_video else "Images", summary.get("total_images", 0), INK),
        ("Workers", summary.get("total_workers", 0), INK),
        ("Safe", summary.get("safe_workers", 0), GREEN),
        ("Unsafe", summary.get("unsafe_workers", 0), RED if summary.get("unsafe_workers") else INK),
        ("Compliance", f"{compliance}%", _tone(compliance)),
    ]

    values = [[str(v) for _, v, _ in cells], [label for label, _, _ in cells]]
    table = Table(values, colWidths=[3.3 * cm] * len(cells), hAlign="LEFT")

    style = [
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, 0), 17),
        ("FONTNAME", (0, 1), (-1, 1), "Helvetica"),
        ("FONTSIZE", (0, 1), (-1, 1), 8),
        ("TEXTCOLOR", (0, 1), (-1, 1), MUTED),
        ("ALIGN", (0, 0), (-1, -1), "CENTER"),
        ("BACKGROUND", (0, 0), (-1, -1), PANEL),
        ("BOX", (0, 0), (-1, -1), 0.5, LINE),
        ("INNERGRID", (0, 0), (-1, -1), 0.5, LINE),
        ("TOPPADDING", (0, 0), (-1, 0), 8),
        ("BOTTOMPADDING", (0, 1), (-1, 1), 8),
    ]
    for index, (_, _, colour) in enumerate(cells):
        style.append(("TEXTCOLOR", (index, 0), (index, 0), colour))
    table.setStyle(TableStyle(style))
    return table


def _missing_ppe_table(summary):
    """Per-item violation counts, worst first. Returns None when clean."""
    counts = [(label, summary.get(key, 0) or 0) for key, label in PPE_ITEMS]
    counts = [(label, count) for label, count in counts if count]
    if not counts:
        return None
    counts.sort(key=lambda row: row[1], reverse=True)

    rows = [["Missing item", "Workers affected"]] + [[label, str(count)] for label, count in counts]
    table = Table(rows, colWidths=[6 * cm, 4 * cm], hAlign="LEFT")
    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), INK),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("TEXTCOLOR", (1, 1), (1, -1), RED),
        ("FONTNAME", (1, 1), (1, -1), "Helvetica-Bold"),
        ("GRID", (0, 0), (-1, -1), 0.5, LINE),
        ("ALIGN", (1, 0), (1, -1), "CENTER"),
        ("TOPPADDING", (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
    ]))
    return table


def _worker_table(workers, cumulative=False):
    """Per-worker PPE checklist: one row per worker, one column per item."""
    if not workers:
        return Paragraph("No workers detected.", _styles()["muted"])

    header = ["Worker"] + [label for _, label in PPE_ITEMS] + ["Status"]
    if cumulative:
        header.insert(1, "Seen in")

    rows = [header]
    status_cells = []

    for index, worker in enumerate(workers, start=1):
        label = f"Worker {worker.get('track_id', worker.get('worker_id', index))}"
        row = [label]
        if cumulative:
            frames = worker.get("frames_seen")
            row.append(f"{frames} frames" if frames else "—")
        for key, _ in PPE_ITEMS:
            row.append("Yes" if worker.get(key) else "No")
        status = worker.get("status", "—")
        row.append(status)
        rows.append(row)
        status_cells.append((index, status))

    widths = [2.6 * cm] + ([2.0 * cm] if cumulative else []) + [1.9 * cm] * len(PPE_ITEMS) + [2.0 * cm]
    table = Table(rows, colWidths=widths, hAlign="LEFT", repeatRows=1)

    style = [
        ("BACKGROUND", (0, 0), (-1, 0), INK),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 8.5),
        ("GRID", (0, 0), (-1, -1), 0.5, LINE),
        ("ALIGN", (1, 0), (-1, -1), "CENTER"),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("TOPPADDING", (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, PANEL]),
    ]

    # Colour the Yes/No cells so a scan of the table reads instantly.
    first_item_col = 2 if cumulative else 1
    for row_index in range(1, len(rows)):
        for offset in range(len(PPE_ITEMS)):
            col = first_item_col + offset
            present = rows[row_index][col] == "Yes"
            style.append(("TEXTCOLOR", (col, row_index), (col, row_index), GREEN if present else RED))
    for row_index, status in status_cells:
        style.append((
            "TEXTCOLOR", (len(header) - 1, row_index), (len(header) - 1, row_index),
            GREEN if status == "Safe" else RED,
        ))
        style.append(("FONTNAME", (len(header) - 1, row_index), (len(header) - 1, row_index), "Helvetica-Bold"))

    table.setStyle(TableStyle(style))
    return table


def _resolve_image_path(image):
    """
    Local path for an annotated frame.

    Records store a URL (http://127.0.0.1:8000/outputs/x.jpg); the file sits
    under the project's outputs/ folder. Video reports also keep only a
    capped set of frames on disk, so a missing file is expected rather than
    exceptional and the caller simply skips the picture.
    """
    url = image.get("annotated") or image.get("original") or ""
    if not url:
        return None
    relative = url.split("127.0.0.1:8000/")[-1].lstrip("/")
    for candidate in (relative, os.path.join(os.path.dirname(__file__), relative)):
        if candidate and os.path.exists(candidate):
            return candidate
    return None


def _scaled_image(path, max_width, max_height):
    """Fit an image inside a box without distorting it."""
    try:
        width, height = ImageReader(path).getSize()
    except Exception:
        return None
    if not width or not height:
        return None
    scale = min(max_width / width, max_height / height)
    return Image(path, width=width * scale, height=height * scale)


def _missing_by_frequency(summary):
    """Items actually missing in this inspection, most affected first."""
    counts = [(label, summary.get(key, 0) or 0) for key, label in PPE_ITEMS]
    return sorted([row for row in counts if row[1]], key=lambda row: row[1], reverse=True)


def _recommendations(summary, is_video):
    """
    Corrective actions for the items that were actually missing.

    The old report printed the same five bullets on every inspection —
    including inspections with no violations at all — which trains readers
    to skip the section entirely. The per-item wording comes from
    risk_engine.get_recommendations, the same source the AI Assistant
    quotes, so advice can't drift between the chat answer and the PDF.
    """
    missing = _missing_by_frequency(summary)

    if not missing:
        return ["All required PPE was detected. No corrective action arises from this inspection."]

    advice = []
    top_label, top_count = missing[0]
    advice.append(
        f"{top_label} was the most frequent gap ({top_count} worker"
        f"{'s' if top_count != 1 else ''} affected) — address this first."
    )
    advice.extend(get_recommendations([label for label, _ in missing]))

    if is_video:
        advice.append(
            "Findings are aggregated across the whole clip: a worker counts as compliant for an "
            "item once it is confirmed in several consecutive frames."
        )

    advice.append("Re-inspect after corrective action to confirm compliance has improved.")
    return advice


def _frame_caption(image, styles):
    """Timestamp + verdict line printed under a contact-sheet thumbnail."""
    stamp = (
        f"{image['timestamp_sec']}s"
        if image.get("timestamp_sec") is not None
        else image.get("name", "frame")
    )
    status = image.get("status", "—")
    colour = "#15803d" if status == "Safe" else "#dc2626"
    missing = ", ".join(image.get("missing", []) or []) or "nothing missing"
    return Paragraph(
        f'<b>{stamp}</b> · <font color="{colour}"><b>{status}</b></font>'
        f' · {image.get("compliance_rate", 0)}%<br/>'
        f'<font size="7.5" color="#64748b">{missing}</font>',
        styles["caption"],
    )


def _frame_grid(frames, styles, columns=2):
    """Frames laid out as a contact sheet, two per row."""
    cells = []
    for image in frames:
        path = _resolve_image_path(image)
        picture = _scaled_image(path, 7.2 * cm, 5.2 * cm) if path else None
        if picture is None:
            picture = Paragraph("Image not retained on disk.", styles["muted"])
        cells.append([picture, _frame_caption(image, styles)])

    flow = []
    for start in range(0, len(cells), columns):
        row = cells[start:start + columns]
        while len(row) < columns:
            row.append(["", ""])  # pad so the table stays rectangular
        data = [[cell[0] for cell in row], [cell[1] for cell in row]]
        table = Table(data, colWidths=[7.8 * cm] * columns, hAlign="LEFT")
        table.setStyle(TableStyle([
            ("ALIGN", (0, 0), (-1, -1), "CENTER"),
            ("VALIGN", (0, 0), (-1, 0), "MIDDLE"),
            ("VALIGN", (0, 1), (-1, 1), "TOP"),
            ("TOPPADDING", (0, 0), (-1, 0), 6),
            ("BOTTOMPADDING", (0, 1), (-1, 1), 10),
        ]))
        flow.append(KeepTogether(table))
    return flow


def _image_block(image, styles):
    """Full detail for a single uploaded photo: picture plus worker table."""
    block = [Paragraph(image.get("name", "Image"), styles["h3"])]

    status = image.get("status", "—")
    block.append(Paragraph(
        f'<font color="{"#15803d" if status == "Safe" else "#dc2626"}"><b>{status}</b></font>'
        f' · {image.get("compliance_rate", 0)}% compliance'
        f' · {image.get("total_workers", 0)} worker(s)'
        f' · Site: {image.get("site_name", "—")}',
        styles["body"],
    ))
    block.append(Spacer(1, 5))

    path = _resolve_image_path(image)
    picture = _scaled_image(path, 12 * cm, 7 * cm) if path else None
    if picture is not None:
        block.append(picture)
        block.append(Paragraph("Annotated detection output", styles["caption"]))
    else:
        block.append(Paragraph("Annotated image not available on disk.", styles["muted"]))

    block.append(Spacer(1, 6))
    block.append(_worker_table(image.get("workers", [])))

    # Actions for this photo's own gaps. An inspection-wide list is useful
    # for the person fixing the site; whoever is looking at one image wants
    # to know what to do about the worker in front of them.
    missing = image.get("missing") or []
    if missing:
        actions = "  ".join(f"• {line}" for line in get_recommendations(missing))
        block.append(Spacer(1, 4))
        block.append(Paragraph(f"<b>Action:</b> {actions}", styles["muted"]))

    return block


def generate_pdf_report(inspection, output_path):
    styles = _styles()
    is_video = (inspection.get("source_type") or "image") == "video"

    doc = SimpleDocTemplate(
        output_path,
        pagesize=A4,
        topMargin=2.2 * cm,
        bottomMargin=1.8 * cm,
        leftMargin=2 * cm,
        rightMargin=2 * cm,
        title="Safesight Inspection Report",
        author="Safesight AI",
    )

    summary = inspection.get("summary", {}) or {}
    images = inspection.get("images", []) or []
    story = []

    # ---------------- Header ----------------
    story.append(Paragraph("Inspection Report", styles["title"]))
    story.append(Paragraph(
        f"{'Video inspection' if is_video else 'Image inspection'} · "
        f"{summary.get('total_workers', 0)} worker(s) assessed",
        styles["subtitle"],
    ))

    # ---------------- Metadata ----------------
    sites = sorted({img.get("site_name") for img in images if img.get("site_name")})
    # Severity of the worst missing item, from the same engine the AI
    # Assistant uses — so a report and a chat answer about the same
    # inspection can't disagree on how serious it is.
    risk_level = assess_risk([label for label, _ in _missing_by_frequency(summary)])

    meta_rows = [
        ["Inspection ID", str(inspection.get("_id", "—"))],
        ["Date", str(inspection.get("timestamp", "—"))],
        ["Site", ", ".join(sites) if sites else "—"],
        ["Risk level", risk_level],
    ]
    if is_video:
        meta_rows.append(["Video file", inspection.get("video_filename") or "—"])
        duration = inspection.get("duration_sec")
        meta_rows.append(["Duration", f"{duration}s" if duration is not None else "—"])
        processed = inspection.get("frames_processed")
        total = inspection.get("frames_total")
        if processed is not None and total:
            sampled = " (sampled evenly across the clip)" if inspection.get("frames_sampled") else ""
            meta_rows.append(["Frames analysed", f"{processed} of {total}{sampled}"])
    story.append(_kv_table(meta_rows, [3.5 * cm, 12 * cm]))
    story.append(Spacer(1, 14))

    # ---------------- Headline numbers ----------------
    story.append(_kpi_row(summary, is_video))
    story.append(Spacer(1, 6))
    story.append(Paragraph(
        "Compliance is the percentage of required PPE items actually detected across all workers, "
        "not the proportion of workers who passed.",
        styles["muted"],
    ))

    # ---------------- Whole-video worker checklist ----------------
    cumulative_workers = inspection.get("workers_cumulative") or []
    if is_video and cumulative_workers:
        story.append(Paragraph("Workers tracked across the video", styles["h2"]))
        story.append(Paragraph(
            "One row per person tracked through the clip. An item counts as present once it has been "
            "confirmed in several frames, so PPE put on partway through is credited.",
            styles["muted"],
        ))
        story.append(Spacer(1, 6))
        story.append(_worker_table(cumulative_workers, cumulative=True))

    # ---------------- Violations ----------------
    story.append(Paragraph("Violation summary", styles["h2"]))
    missing_table = _missing_ppe_table(summary)
    if missing_table is not None:
        story.append(missing_table)
    else:
        story.append(Paragraph("No PPE violations were detected in this inspection.", styles["body"]))

    # ---------------- Recommendations ----------------
    story.append(Paragraph("Recommended actions", styles["h2"]))
    for line in _recommendations(summary, is_video):
        story.append(Paragraph(f"• {line}", styles["body"]))
        story.append(Spacer(1, 3))

    # ---------------- Evidence ----------------
    if images:
        shown = images
        note = None
        if is_video and len(images) > MAX_VIDEO_FRAMES_IN_REPORT:
            unsafe = [img for img in images if img.get("status") == "Unsafe"]
            safe = [img for img in images if img.get("status") != "Unsafe"]
            shown = (unsafe + safe)[:MAX_VIDEO_FRAMES_IN_REPORT]
            shown.sort(key=lambda img: img.get("frame_index", 0))
            note = (
                f"Showing {len(shown)} of {len(images)} retained frames, violations first. "
                "The figures above cover the whole video."
            )

        # Only force a fresh page when there's enough evidence to fill one.
        # A single-image inspection has a third of a page of summary, and
        # an unconditional break stranded the rest of it and pushed the one
        # photo onto page 2 for no reason.
        if len(shown) > 1 or is_video:
            story.append(PageBreak())
        else:
            story.append(Spacer(1, 10))

        story.append(Paragraph("Frame evidence" if is_video else "Image evidence", styles["h2"]))
        if note:
            story.append(Paragraph(note, styles["muted"]))
        if is_video:
            # Without this, a reader hitting a frame marked 20% right after a
            # whole-video row showing helmet/vest/gloves present reasonably
            # concludes the report contradicts itself. Both are true: one is
            # an instant, the other is the clip.
            story.append(Paragraph(
                "Each frame below is judged on that instant alone, so a frame can show fewer items "
                "than the whole-video figures above — PPE is only visible to the detector when it "
                "faces the camera and isn't blurred or obscured.",
                styles["muted"],
            ))
        story.append(Spacer(1, 4))

        if is_video:
            # Contact sheet. Video frames are one continuous scene, so what a
            # reader wants is a visual timeline they can scan — and the
            # per-worker detail is already covered by the cumulative table
            # above, making a worker table under every frame pure repetition.
            # A full-width block per frame also stranded most of each page.
            story.extend(_frame_grid(shown, styles))
        else:
            # Separate photos, each its own scene: full detail per image.
            for image in shown:
                story.append(KeepTogether(_image_block(image, styles)))
                story.append(Spacer(1, 14))

    doc.build(story, onFirstPage=_page_furniture, onLaterPages=_page_furniture)
